#!/usr/bin/env python3
from main import main


if __name__ == "__main__":
    main()


# file = open(kitty_dir, "r")
# kitty = open("/home/fredvel/.config/kitty/colorscheme/set-colorscheme.conf", "r")

# print(file.read())
# file.close()

# theme = input("your theme: ")
# print(kitty.read())

# if theme == "gotham":
# gotham = 'require("config/colorschemes/gotham")'
# file.write(gotham)
# gotham_kitty = "include ./gotham.conf"
# kitty.write(gotham_kitty)
# print("your theme was updated")
# elif theme == "tokyo":
# tokyo = 'require("config/colorschemes/tokyo")'
# file.write(tokyo)
# print("your theme was updated")
# elif theme == "nightfly":
# nightfly = 'require("config/colorschemes/nightfly")'
# gotham_kitty = "include ./nightfly.conf"
# file.write(nightfly)
# kitty.write(gotham_kitty)
# print("your theme was updated")
# elif theme == "onedark":
# onedark_vim = 'require("config/colorschemes/onedarkpro")'
# onedark_kitty = "include ./one-dark-pro.conf"
# file.write(onedark_vim)
# kitty.write(onedark_kitty)
# print("your theme was updated")

# else:
# print('error')
